[features]
seeds = false
skip-lint = false


[programs.localnet]
counter_program = "EqJhqVA7kssaFNXswwXJyrqViERu9a7ZmpGhy2duQ64u"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
client = "yarn run ts-node client/*.ts"